### ISSUE TITLE
How does UDOT handle space?

### ISSUE THREAD

**Issue by tiborvass** [NieDzejkob/miniforth#1]
In your blogpost you mention:

> The space is printed by pushing a fake "digit" that will get converted into a space.

but if I read correctly https://github.com/NieDzejkob/miniforth/blob/2842b9a303c07d8d8ace8dc890c531d55866348e/boot.s#L326-L345 

You go:
- from `" " - "0" = 32 - 48 = -16` https://github.com/NieDzejkob/miniforth/blob/2842b9a303c07d8d8ace8dc890c531d55866348e/boot.s#L328
- to `-16 + "0" = 32` https://github.com/NieDzejkob/miniforth/blob/master/boot.s#L337
- to `32 + "A" - "0" - 10 = 32 + 65 - 48 - 10 = 39 ≠ 32` https://github.com/NieDzejkob/miniforth/blob/2842b9a303c07d8d8ace8dc890c531d55866348e/boot.s#L340

Am I missing something or should `"A" - "0" - 10` be `"A" - "0" - 17` ?

**Comment by NieDzejkob** [comment]
The part that that adds "A" - "0" - 10 won't run because 32 is less than
"9" = 57.

**Comment by tiborvass** [comment]
🤦 I need to sleep !!! Sorry!
