### ISSUE TITLE
can you use rv32i as the target ISA for demo?

### ISSUE THREAD

**Issue by yunfan** [NieDzejkob/miniforth#2]
this project is super cool, but x86 assembly is a huge and complex.
is it possible to use riscv assmbly to rewritten this so people who dont know assembly lang before could understand(by a crash course) and extend it easily?

**Comment by NieDzejkob** [comment]
I don't think x86 is particularly harder than rv32i. Does the RISC-V environment use something like a BIOS that would provide keyboard, monitor and disk support? I doubt it'd fit in a similar size otherwise.

Perhaps some other Forth has a RISC-V port?

**Comment by yunfan** [comment]
@NieDzejkob i think for a completely newbie (consider nowaday most programer dont start from assembly language), rv32i is easy than x86. 
and there is qemu support for it
