### ISSUE TITLE
Image releases?

### ISSUE THREAD

**Issue by Shadlock0133** [NieDzejkob/miniforth#4]
Have you thought about using github releases to publish assembled disk image? I wanted to try it out, but setting up build environment on windows is kinda difficult. I will try setting up a linux vm, but having it prebuilt would be nice.

P.S. I've really enjoyed reading your articles. They motivate me to work on my (tangentially related) project \:)

**Comment by NieDzejkob** [comment]
Thanks for the suggestion! Disk images are now available for download.
